<program> ::= <identifier>  ":" <block> ENDP <identifier>

<block> ::= DECLARATIONS <declaration_block> CODE <statement_block>

<declaration_block> ::= <identifier_block>  OF TYPE <type> ";" 
					  | <identifier_block>  OF TYPE <type> ";" <declaration_block>

<identifier_block> ::= <identifier> | <identifier> "," <identifier_block>

<type> ::= CHARACTER | INTEGER | REAL

<statement_block> ::= <statement> ";" <statement_block> | <statement>

<statement> ::= <assignment_statement>
			  | <if_statement>
			  | <do_statement>
			  | <while_statement>
			  | <for_statement>
			  | <write_statement>
			  | <read_statement>
			  
<assignment_statement> ::= <expression> "->" <identifier>

<if_statement> ::= IF <conditional> THEN <statement_block> ENDIF
			     | IF <conditional> THEN <statement_block> ELSE <statement_block> ENDIF
			  
<do_statement> ::= DO <statement_block> WHILE <conditional> ENDDO

<while_statement> ::= WHILE <conditional> DO <statement_block> ENDWHILE

<for_statement> ::= FOR <identifier> IS <expression> BY <expression> TO <expression>
								     DO <statement_block> ENDFOR

<write_statement> ::= WRITE "(" <output_block> ")" 
					| NEWLINE
					
<read_statement> ::= READ "(" <identifier> ")"

<output_block> ::= <value> "," <output_block> 
				| <value>

<conditional> ::= <expression> <comparator> <expression>
				| NOT <conditional>
				| <expression> <comparator> <expression> AND <conditional>
				| <expression> <comparator> <expression> OR <conditional>

<comparator> ::= "=" | "<>" | "<" | ">" | "<=" | ">="

<expression> ::= <expression> "+" <term>
			   | <expression> "-" <term>
			   | <term> 

<term> ::= <term> "+" <value>
		 | <term> "-" <value>
		 | <value>

<value> ::= <identifier> 
		  | <constant>
		  | "(" <expression> ")"

<constant> ::= <number_constant> | <character_contstant>

<character_contstant> "'" <character> "'"

<number_constant> ::= <integer> 
					| "-" <integer> 
					| <integer> "." <integer>
					| "-"  <integer> "." <integer>

<integer> ::= <digit> | <digit> <integer>					
			  
<identifier> ::= <character> 
			  | <identifier> <character>
			  | <identifier> <digit>
			 
<character> ::= a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z
				A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z

<digit> ::= 0|1|2|3|4|5|6|7|8|9|0
			 
			  